### ISSUE TITLE
segfault on osx from minimal program when multiple devices connected

### ISSUE THREAD

**Issue by rambo** [jerry73204/realsense-rust#3] opened 2020-04-08 11:30 UTC
```rust
use failure::Fallible;
use realsense_rust;

fn main() -> Fallible<()> {
    println!("Hello, world!");
    let pipeline = realsense_rust::Pipeline::new()?;
    let config = realsense_rust::Config::new()?;
    let mut pipeline = pipeline.start(Some(config))?;

    let profile = pipeline.profile();
    for (idx, stream_result) in profile.streams()?.try_into_iter()?.enumerate() {
        let stream = stream_result?;
        println!("stream data {}: {:#?}", idx, stream.get_data()?);
    }

    Ok(())
}
```

unfortunately `gdb` backtrace was completely useless (it seems it doesn't find any debug symbols).

On arm64 linux that does not segfault, it lists profile from one of the connected devices (which I think is the expected behaviour).

**Comment by rambo** [comment] 2020-04-08 11:32
this minimal program works just fine on osx, btw:

```rust
use failure::ensure;
use failure::Fallible;

fn main() -> Fallible<()> {
    println!("Looking for RealSense devices");
    let ctx = realsense_rust::Context::new()?;
    let devices = ctx.query_devices(None)?;
    let mut devices_found: bool = false;
    for device in devices {
        let device = device.unwrap();
        let name = device.name().unwrap().unwrap();
        let sn = device.serial_number().unwrap().unwrap();
        println!("Found {} SN {}", name, sn);
        devices_found = true;
    }
    ensure!(devices_found, "No devices found");
    Ok(())
}
```

**Comment by jerry73204** [comment] 2020-04-13 06:38
Unfortunately, I don't have a mac to investigate this issue.
I suspect the issue stems from the wrong de-allocation order. Perhaps you can try block wrapping to force the order of `Drop::drop` to see if my guess is correct.

```rust
{
    let ctx = Context::new();
    {
        let devices = ctx.query_devices(None)?;
        // omit ...
    } // drop devices
} // drop ctx
```

BTW, use this annotation to enable syntax highlighting in GitHub. (ignore the '\' below pls)

```
\```rust
\```
```

**Comment by rambo** [comment] 2020-04-14 08:25
The problem might actually be in Intels librealsense side, I think I managed to trigger a segfault with a similar thing in C++. But I've done so many things around this at the same time I can't be sure and right now can't dedicate time for detailed testing.

**Comment by jerry73204** [comment] 2020-07-13 11:34
Perhaps it is connected to #6. I guess the default config connnects to the same device and it leads to segfault. I'm sorry that I don't have a mac and have only single device here. So if possible, I'm interested if the release could fix this issue.

**Comment by jerry73204** [comment] 2021-02-27 02:26
The issue is fixed in Tangram Vision's repo and the original repository is no longer maintained.

Please move to the new repository.

https://gitlab.com/tangram-vision-oss/realsense-rust

**Closed as completed by jerry73204** 2021-02-27 02:26 UTC
